### ISSUE TITLE
Installation error on Windows10 - 64 bit - Python 3.8.12

### ISSUE THREAD

**Issue by jmargutt** [muety/pyquadkey2#8]
Collecting pyquadkey2
  Downloading pyquadkey2-0.2.0.tar.gz (40 kB)
     |████████████████████████████████| 40 kB 2.7 MB/s
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\JMargutti\Anaconda3\envs\typhoon\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JMargutti\\AppData\\Local\\Temp\\pip-install-275rjrt3\\pyquadkey2_03b779f2444d4d2aa98e3a0637
c6c0f0\\setup.py'"'"'; __file__='"'"'C:\\Users\\JMargutti\\AppData\\Local\\Temp\\pip-install-275rjrt3\\pyquadkey2_03b779f2444d4d2aa98e3a0637c6c0f0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(_
_file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\JMargutti\AppData\L
ocal\Temp\pip-pip-egg-info-60bsa_hu'
       cwd: C:\Users\JMargutti\AppData\Local\Temp\pip-install-275rjrt3\pyquadkey2_03b779f2444d4d2aa98e3a0637c6c0f0\
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\JMargutti\AppData\Local\Temp\pip-install-275rjrt3\pyquadkey2_03b779f2444d4d2aa98e3a0637c6c0f0\setup.py", line 11, in <module>
      long_description = fh.read()
    File "C:\Users\JMargutti\Anaconda3\envs\typhoon\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5: character maps to <undefined>
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f2/5e/671b87ea0da1066e5b65ab32ef7efb6ca5f8d0ce894e5dc3a60dc53f4c13/pyquadkey2-0.2.0.tar.gz#sha256=0ab7919384d2b5a1f81e427fe94fb9d223fc4de7bfd91f2327db54217f8ee757 (from https:
//pypi.org/simple/pyquadkey2/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyquadkey2-0.1.1.tar.gz (43 kB)
     |████████████████████████████████| 43 kB ...
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\JMargutti\Anaconda3\envs\typhoon\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JMargutti\\AppData\\Local\\Temp\\pip-install-275rjrt3\\pyquadkey2_6cd07c82e19b4c03b362eb46c8
c616b5\\setup.py'"'"'; __file__='"'"'C:\\Users\\JMargutti\\AppData\\Local\\Temp\\pip-install-275rjrt3\\pyquadkey2_6cd07c82e19b4c03b362eb46c8c616b5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(_
_file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\JMargutti\AppData\L
ocal\Temp\pip-pip-egg-info-mmvq4hz_'
       cwd: C:\Users\JMargutti\AppData\Local\Temp\pip-install-275rjrt3\pyquadkey2_6cd07c82e19b4c03b362eb46c8c616b5\
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\JMargutti\AppData\Local\Temp\pip-install-275rjrt3\pyquadkey2_6cd07c82e19b4c03b362eb46c8c616b5\setup.py", line 11, in <module>
      long_description = fh.read()
    File "C:\Users\JMargutti\Anaconda3\envs\typhoon\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5: character maps to <undefined>
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c9/0d/ad4ec0d25068085df9d476da1476215e1a73e882c116a9d06baac2f644bb/pyquadkey2-0.1.1.tar.gz#sha256=6c32b4fb8a3a7311b68f3b8d209d4dbdce4c70ca3eb2a833c4bc8611194fb60a (from https:
//pypi.org/simple/pyquadkey2/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyquadkey2 (from versions: 0.1.1, 0.2.0)
ERROR: No matching distribution found for pyquadkey2

**Comment by d3netxer** [comment]
I have a similar problem trying to install on Python 3.8.8. The last 7 lines of my error:
```
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c9/0d/ad4ec0d25068085df9d476da1476215e1a73e882c116a9d06baac2f644bb/pyquadkey2-0.1.1.tar.gz#sha256=6c32b4fb8a3a7311b68f3b8d209d4dbdce4c70ca3eb2a833c4bc8611194fb60a (from https://pypi.org/simple/pyquadkey2/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyquadkey2
ERROR: No matching distribution found for pyquadkey2
```

**Comment by d3netxer** [comment]
However, installing from archive works:

From archive
$ wget https://github.com/muety/pyquadkey2/releases/download/0.2.1/pyquadkey2-0.2.1.tar.gz
$ pip install pyquadkey2-0.2.1.tar.gz

**Comment by tanm14** [comment]
i have similar error installing to my Python 3.7.1 on Windows. Seems like it is an encoding issue that happens on windows machine.  @d3netxer , thanks for your tips. Installing the version from your link works.

Error log as below. 

Collecting pyquadkey2
  Downloading pyquadkey2-0.2.0.tar.gz (40 kB)
     |████████████████████████████████| 40 kB 1.3 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\py36\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TANM~1.14\\AppData\\Local\\Temp\\pip-install-en8tfldn\\pyquadkey2_f2becb880f1e46d59df601a408d1b0bf\\setup.py'"'"'; __file__='"'"'C:\\Users\\TANM~1.14\\AppData\\Local\\Temp\\pip-install-en8tfldn\\pyquadkey2_f2becb880f1e46d59df601a408d1b0bf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\TANM~1.14\AppData\Local\Temp\pip-pip-egg-info-br5noucm'
         cwd: C:\Users\TANM~1.14\AppData\Local\Temp\pip-install-en8tfldn\pyquadkey2_f2becb880f1e46d59df601a408d1b0bf\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\TANM~1.14\AppData\Local\Temp\pip-install-en8tfldn\pyquadkey2_f2becb880f1e46d59df601a408d1b0bf\setup.py", line 11, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 1026: illegal multibyte sequence
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f2/5e/671b87ea0da1066e5b65ab32ef7efb6ca5f8d0ce894e5dc3a60dc53f4c13/pyquadkey2-0.2.0.tar.gz#sha256=0ab7919384d2b5a1f81e427fe94fb9d223fc4de7bfd91f2327db54217f8ee757 (from https://pypi.org/simple/pyquadkey2/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyquadkey2-0.1.1.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 590 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\py36\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TANM~1.14\\AppData\\Local\\Temp\\pip-install-en8tfldn\\pyquadkey2_ff53082fdf7b472c9a0e0988f7c1acc9\\setup.py'"'"'; __file__='"'"'C:\\Users\\TANM~1.14\\AppData\\Local\\Temp\\pip-install-en8tfldn\\pyquadkey2_ff53082fdf7b472c9a0e0988f7c1acc9\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\TANM~1.14\AppData\Local\Temp\pip-pip-egg-info-y1c2_hrg'
         cwd: C:\Users\TANM~1.14\AppData\Local\Temp\pip-install-en8tfldn\pyquadkey2_ff53082fdf7b472c9a0e0988f7c1acc9\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\TANM~1.14\AppData\Local\Temp\pip-install-en8tfldn\pyquadkey2_ff53082fdf7b472c9a0e0988f7c1acc9\setup.py", line 11, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 1026: illegal multibyte sequence
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c9/0d/ad4ec0d25068085df9d476da1476215e1a73e882c116a9d06baac2f644bb/pyquadkey2-0.1.1.tar.gz#sha256=6c32b4fb8a3a7311b68f3b8d209d4dbdce4c70ca3eb2a833c4bc8611194fb60a (from https://pypi.org/simple/pyquadkey2/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyquadkey2 (from versions: 0.1.1, 0.2.0)
ERROR: No matching distribution found for pyquadkey2
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\py36\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\py36\lib\site-packages)
